- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: ansible_system != 'Win32NT'

- name: restart assessment-agent
  ansible.builtin.systemd:
    name: "{{ agent_service_name }}"
    state: restarted
  listen: restart assessment-agent
  when: ansible_system != 'Win32NT'

- name: restart AssessmentAgent
  ansible.windows.win_service:
    name: "{{ agent_service_name }}"
    state: restarted
  listen: restart AssessmentAgent
  when: ansible_system == 'Win32NT'
