- name: Load OS vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install nginx (Debian)
  ansible.builtin.apt:
    name: "{{ svc_pkg }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Install nginx (RedHat)
  ansible.builtin.dnf:
    name: "{{ svc_pkg }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Enable and start nginx
  ansible.builtin.systemd:
    name: "{{ svc_name }}"
    enabled: true
    state: started
